In [16]:
import numpy as np
import pandas as pd

a1 = np.array([1, 2, 3])

a2 = np.array([[1, 2, 3],
              [4, 5, 6]])

a3 = np.array([[[1, 2, 2.3],
                [3, 3.4, 4],
                [2, 4.3, 5]],

                [[0, 2, 2.3],
                [2, 2.2, 4],
                [2, 3.2, 5]]]
              )
a1       # Matriks Değerleri
a1.shape # Matriks Boyutları, Matriks Veri Türü
a2.ndim  # Matriks Kaç Boyutlu Olduğu Bilgisi
a1.dtype # Matriks Veri Türü
a1.size  # Matriks Boyutu

df = pd.DataFrame(a2) # Pandas veri aktarılmasını sağlar.
df

0  1  2
0  1  2  3
1  4  5  6

`np.random` kod her çalıştırıldığında farklı değerler üretir. Her çalıştırdığımızda aynı değerlerin oluşması için `np.random.seed(7)` kullanılır.

In [20]:
# Birlerden oluşan dizin, shape boyutunu, dtype ise
# türünü belirtir default olarak float64
one_array = np.ones(shape = (2, 4), dtype = int) 
zeros_array = np.zeros((2, 3, 4)) # Sıfırdan oluşan
range_array = np.arange(0, 20, 5) # Belirli bir aralıkta belirli artış miktarına göre oluşturur.

random_array_1 = np.random.randint(0, 10, size=(2,4))
random_array_2 = np.random.random((2,4)) # 0.0 - 1.0 arasında sayılar oluşturur.
random_array_3 = np.random.rand(2,4)
one_array, one_array.dtype, zeros_array

(array([[1, 1, 1, 1],
        [1, 1, 1, 1]]),
 dtype('int64'),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]))

- Erişim için `[,]` şeklinde ilerlenir.
- Diziler üstünde aritmatik işlemler yapılabilir. (+, -, *, /, //, **, %)
- `np.exp, np.log, np.sum, np.mean, np.max, np.min, np.std, np.var, np.sqrt` vb matamatiksel fonksiyonları kullanılabilir.
- `sort` sıralamayı sağlar. `argsort` sıralama sonucunda sayıların gerçekte hangi index de olduğunu belirtir.

In [26]:
a1 = np.random.randint(1, 10, size=(2, 3, 3))
a2 = np.ones((2, 3, 3))
a1 + a2 # ya da np.add(a1, a2)
a1 ** a2 # ya da np.square(a1, a2)
a1[:2, :2, :2]


array([[[1, 5],
        [2, 7]],

       [[1, 1],
        [5, 1]]])

In [29]:
a1 = np.random.randint(1, 23, (3, 4))
a1, np.sort(a1), np.argsort(a1), np.argmax(a1), np.argmin(a1)

(array([[ 8,  3, 18,  1],
        [22, 18,  3, 10],
        [14, 17, 19, 16]]),
 array([[ 1,  3,  8, 18],
        [ 3, 10, 18, 22],
        [14, 16, 17, 19]]),
 array([[3, 1, 0, 2],
        [2, 3, 1, 0],
        [0, 3, 1, 2]]),
 4,
 3)

- Skaleer çarpımda a1 * a2 olabilmesi için boyutlarının uyumlu olması lazımdır. `reshape` yeniden boyutlandırmayı sağlar.
- Vektorel çarpımda `(a,b)x(b,c) = (a,c)` şeklinde boyutları olması lazımdır.
- **Transpose=** eksenlerin yer değiştirmesini sağlar.

In [32]:
a1 = np.random.randint(1, 10, size=(2, 3, 3))
a2 = np.random.randint(1, 10, size=(2, 3))
a2_reshape = a2.reshape(2, 3, 1)
a2.shape, a2.T.shape

((2, 3), (3, 2))

In [34]:
a3 = np.random.randint(5, size=(4, 3))
a4 = np.random.randint(5, size=(3, 2))
np.dot(a3, a4) # Vektorel çarpım

array([[3, 0],
       [7, 2],
       [7, 4],
       [3, 0]])

In [33]:
a5 = np.random.randint(1, 10, (3, 4))
a6 = np.random.randint(1, 10, (3, 4))
a5, a6, a5 >= a6

(array([[5, 2, 2, 6],
        [3, 9, 2, 8],
        [9, 3, 2, 1]]),
 array([[7, 9, 1, 2],
        [1, 1, 2, 7],
        [1, 3, 7, 5]]),
 array([[False, False,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True, False, False]]))